### PR TITLE
Too many things ...

### PR DESCRIPTION
**Pull request by DronCode**

### CODE REVIEW

**Comment by ipoopedmypantsuups** [comment]
Hey, are you guys still working on this? Be nice to see some updates. Also it looks like the Release you guys released is missing some features :( What's up?

**Comment by garstas** [comment]
```cpp
hitman is Glacier::ZLNKWHANDS
hitman->GetRHandWeapon()->m_isVisibleForNPCs
```
`error C2027: use of undefined type "Glacier::ZItemWeapon"`/`error C2027: use of undefined type "Glacier::ZItem"`

I guess items definition should be added here
```cpp
// in ReHitman\Glacier\include\Glacier\IK\ZLNKWHANDS.h
#include <Glacier/Items/ZItemWeapon.h>
```

**Comment by DronCode** [comment]
@godstanis, no, this type was forward declared in `#include <Glacier/GlacierFWD.h>`, in your code you should include `#include <Glacier/Items/ZItemWeapon.h>` to use method `GetRHandWeapon`

**Comment by DronCode** [comment]
Looks like it is almost ready to merge :godmode:

**Comment by DronCode** [comment]
Ok, let's merge this right now 😆

**Comment by DronCode** [comment]
It's done, will test later.

**Pull request merged**
